add stale-bot
fivetran/dbt_package_automations pull request #21
Opened 2024-07-24 17:11 UTC by fivetran-catfritz

Add a bot to manage staleness of issue and prs.

2024-08-14 14:33 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz we saw this in action [here](https://github.com/fivetran/dbt_starter_project/issues/38) and I believe this will be a great addition to our maintenance tool belt! 

I have a few comments and suggestions below before this will be ready to be merged. Many of my suggestions are wording changes. We can also discuss the wording in more detail with the team before rolling this out.

2024-08-14 14:33 UTC, fivetran-joemarkiewicz commented on .github/workflows/stale-bot.yml
> +  CLOSE_PR_MSG: "Although we are closing this PR as stale, it can still be reopened to continue development. Just add a comment to notify the maintainers."
```suggestion
  CLOSE_PR_MSG: "We're closing this PR due to inactivity, but it can easily be reopened if there's renewed interest from the community. Just drop a comment to let the maintainers know. Thanks for your understanding!"
```

2024-08-14 14:33 UTC, fivetran-joemarkiewicz commented on .github/workflows/stale-bot.yml
> +          days-before-close: 1 #using 1 for testing, but before merge we want it to be more like 30
I find 180 days is too long. I believe shortening the window to 90 days and giving another 30 is an appropriate window. Let me know if you disagree.

```suggestion
          days-before-stale: 90
          days-before-close: 30
```

2024-08-14 14:33 UTC, fivetran-joemarkiewicz commented on .github/workflows/stale-bot.yml
> +          exempt-pr-labels: 'pinned'
Can you explain what the pinned exempt labels are?

2024-08-14 14:33 UTC, fivetran-joemarkiewicz commented on .github/workflows/stale-bot.yml
> +  pull-requests: write
I see in the Issue that a user "github-actions" is posting in the issues. I don't see anywhere that we are creating this user or granting permission other than right here. Is this "github-actions" user a native GitHub bot that all repos have access to? Just looking to understand this a bit more.

2024-08-14 15:14 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz Thanks for the comments! I committed all your suggestions, and let me know if you want to change what we use for the "pinned" label.

2024-08-14 15:14 UTC, fivetran-catfritz commented on .github/workflows/stale-bot.yml
> +  pull-requests: write
Yes, this is a Github authored action. [Here](https://github.com/actions/stale) is the repo for the action, and [this](https://github.com/actions) is the broader actions page. Also I noticed if you click on the bot it takes you to Github, so I would say all signs point to Github native!

2024-08-14 15:14 UTC, fivetran-catfritz commented on .github/workflows/stale-bot.yml
> +          days-before-close: 1 #using 1 for testing, but before merge we want it to be more like 30
No strong opinion here--agreed!

2024-08-14 15:14 UTC, fivetran-catfritz commented on .github/workflows/stale-bot.yml
> +          exempt-pr-labels: 'pinned'
Ahh yes. If we want to prevent an issue from getting auto-closed, you can add the label "pinned", and the action will ignore that issue. I picked this label, so we can change it to anything else.

2024-08-14 15:19 UTC, fivetran-joemarkiewicz commented
@fivetran-catfritz thanks for addressing all of my comments and helping inform me on the nature of the GitHub bot. Lastly, do you know if this automation starts tracking days after it's been implemented, or does it retroactively count the days? For example when we add this bot to a repo will it mark an existing issue from 2 years ago as stale? If so, we should probably do an audit of issues on each repo before releasing this action to ensure we are pinning issues that should be. 

I like using the pinned label, but let's make sure we add it to each repo and include a description of the label. We can address this during the mass package update.

2024-08-14 16:09 UTC, fivetran-catfritz commented
@fivetran-joemarkiewicz When the action runs each day, it looks at the "updated_at" field for the issue to determine staleness ([this section](https://github.com/actions/stale?tab=readme-ov-file#days-before-stale) of their readme explains it also), so yes for each repo it should mark existing issues. For example, it marked [this test issue](https://github.com/fivetran/dbt_starter_project/issues/11) from 2 years ago as stale and closed.

And sounds good re the pinned labels!

2026-01-21 23:31 UTC, fivetran-catfritz commented
Closing as this is superseded by #31

2026-01-21 23:31 UTC, closed without merging